export const coffeeDescriptions = {
  Ethiopia: {
    country: 'Ethiopia',
    color: 'green',
    farm: 'Nguisse Nare',
    tastingNotes: 'Lavendar, plum, peach, rose water',
    processing: 'Natural',
    lot: 'Nguisse Nare, Bombe, Natural, Grade 1',
    region: 'Sidama Bensa Bombe',
    varietals: '74158',
    altitude: '2,240 meters',
    size: '12',
    traceable: 'Nguisse Nare and 60 registered outgrowers',
  },

  Mexico: {
    country: 'Mexico',
    color: 'orange',
    farm: 'Red 5 de Diciembre',
    tastingNotes: 'Lemon, earl grey, caramel, peach, honey',
    processing: 'Washed',
    lot: 'Red 5 de Diciembre, Eloxochitlán de Flores Magón Barrio de Buenavista Washed',
    region: 'Mazatec, Oaxaca, La Canada',
    varietals: 'Costa Rica 95, Obatã',
    altitude: '1,650 meters',
    size: '12',
    traceable: '1,420 smallholders',
  },

  Colombia: {
    country: 'Colombia',
    color: 'sky',
    farm: 'Federacion Abades',
    tastingNotes: 'Red apple, quince, caramel, sugar plum',
    processing: 'Washed',
    lot: 'Federacion Abades, Samaniego Lot 9',
    region: 'Nariño',
    varietals: 'Castillo and Colombia',
    altitude: '1,800 - 1,850 meters',
    size: '12',
    traceable: '206 smallholder members',
  },

  Brazil: {
    country: 'Brazil',
    color: 'yellow',
    farm: 'Marcelo Assis',
    tastingNotes: 'Grapefruit, lemon liquor, cherry, chocolate',
    processing: 'Natural',
    lot: 'Marcelo Assis, Fazenda Bioma Red Catuai Natural PB Lot 58',
    region: 'Cerrado Mineiro, Campos Altos',
    varietals: 'Red Catuaí',
    altitude: '1,206 meters',
    size: '10',
    traceable: 'Marcelo Assis, Fazenda Bioma',
  },

  Sumatra: {
    country: 'Sumatra',
    color: 'rose',
    farm: 'Solok Radjo',
    tastingNotes: 'chocolate pomegeanate aroma, spritzy pear acidity, roobois',
    processing: 'Honey / Pulped Natural',
    lot: 'Solok Radjo Honey',
    region: 'Unknown',
    varietals: 'Lini S795',
    altitude: '1,200-1,600 meters',
    size: '12',
    traceable: 'Cooperative',
  },

  EthiopiaDecaf: {
    country: 'Ethiopia',
    color: 'slate',
    farm: 'Duromina Cooperative',
    tastingNotes: 'chocolate babka aroma, mint, caramel, cherries',
    processing: 'Swiss water processed decaf',
    lot: 'Duromina Cooperative Decaf',
    region: 'Limu, Agaro',
    varietals: 'Heirloom',
    altitude: '1,980 - 2,100 meters',
    size: '12',
    traceable: '329 Members',
  },

  Totutla: {
    country: 'Mexico',
    color: 'cyan',
    farm: 'Red de Totutla',
    tastingNotes:
      'Almond, chocolate covered white cherry, chardonnay, raisin, lemon',
    processing: 'Washed',
    lot: 'Totutla Community',
    region: 'Totula, Puebla',
    varietals: 'Typica, Bourbon, Caturra',
    altitude: '1200 - 1450',
    size: '10',
    traceable: '11 Families',
  },
};
