export const coffeeDescriptions = {
  Ethiopia: {
    country: 'Ethiopia',
    color: 'green',
    farm: 'Nguisse Nare',
    tastingNotes: 'Lavendar, plum, peach, rose water',
    processing: 'Natural',
    lot: 'Nguisse Nare, Bombe, Natural, Grade 1',
    region: 'Sidama Bensa Bombe',
    varietals: '74158',
    altitude: '2,240 meters',
    size: '12',
    traceable: 'Nguisse Nare and 60 registered outgrowers',
  },

  Mexico: {
    country: 'Mexico',
    color: 'orange',
    farm: 'Red 5 de Diciembre',
    tastingNotes: 'Lemon, earl grey, caramel, peach, honey',
    processing: 'Washed',
    lot: 'Red 5 de Diciembre, Eloxochitlán de Flores Magón Barrio de Buenavista Washed',
    region: 'Mazatec, Oaxaca, La Canada',
    varietals: 'Costa Rica 95, Obatã',
    altitude: '1,650 meters',
    size: '12',
    traceable: '1,420 smallholders',
  },

  Colombia: {
    country: 'Colombia',
    color: 'sky',
    farm: 'Federacion Abades',
    tastingNotes: 'Red apple, quince, caramel, sugar plum',
    processing: 'Washed',
    lot: 'Federacion Abades, Samaniego Lot 9',
    region: 'Nariño',
    varietals: 'Castillo and Colombia',
    altitude: '1,800 - 1,850 meters',
    size: '12',
    traceable: '206 smallholder members',
  },

  Brazil: {
    country: 'Brazil',
    color: 'yellow',
    farm: 'Marcelo Assis',
    tastingNotes: 'Grapefruit, lemon liquor, cherry, chocolate',
    processing: 'Natural',
    lot: 'Marcelo Assis, Fazenda Bioma Red Catuai Natural PB Lot 58',
    region: 'Cerrado Mineiro, Campos Altos',
    varietals: 'Red Catuaí',
    altitude: '1,206 meters',
    size: '10',
    traceable: 'Marcelo Assis, Fazenda Bioma',
  },

  Sumatra: {
    country: 'Sumatra',
    color: 'rose',
    farm: 'Solok Radjo',
    tastingNotes: 'chocolate pomegeanate aroma, spritzy pear acidity, roobois',
    processing: 'Honey / Pulped Natural',
    lot: 'Solok Radjo Honey',
    region: 'Unknown',
    varietals: 'Lini S795',
    altitude: '1,200-1,600 meters',
    size: '12',
    traceable: 'Cooperative',
  },

  EthiopiaDecaf: {
    country: 'Ethiopia',
    color: 'slate',
    farm: 'Duromina Cooperative',
    tastingNotes: 'chocolate babka aroma, mint, caramel, cherries',
    processing: 'Swiss water processed decaf',
    lot: 'Duromina Cooperative Decaf',
    region: 'Limu, Agaro',
    varietals: 'Heirloom',
    altitude: '1,980 - 2,100 meters',
    size: '12',
    traceable: '329 Members',
  },

  KenyaNyeriGichichiAA: {
    country: 'Kenya',
    price: 28,
    score: 91,
    color: 'amber',
    farm: 'Gichichi AA',
    lot: '19',
    size: '8 oz',
    region: 'Gichichi, Nyeri County',
    processing: 'Washed',
    varietals: 'Bourbon',
    traceable: '477 Farms',
    altitude: '1800 meters',
    tastingNotes: 'Sugar cane, Dried ginger, Green tea, Lime zest',
  },

  EthiopiaYirgacheffeBankoGotiti: {
    country: 'Ethiopia Yirgacheffe',
    color: 'emerald',
    farm: 'Banko Gotti Gr 1',
    tastingNotes: 'Jasmine, Lavender, Fresh rue, Rosemary',
    processing: 'Natural',
    lot: '100',
    region: 'Banko Gotiti, YirgaCheffe',
    varietals: 'Heirloom',
    size: '8 oz',
    traceable: '320 farmers',
    altitude: '2059 meters',
    score: 91.5,
  },

  MexicoTotutla: {
    country: 'Mexico',
    color: 'cyan',
    farm: 'Red de Totutla',
    tastingNotes:
      'Almond, chocolate covered white cherry, chardonnay, raisin, lemon',
    processing: 'Washed',
    lot: 'Totutla Community',
    region: 'Totutla, Puebla',
    varietals: 'Typica, Bourbon, Caturra',
    size: '100g',
    traceable: '11 families',
    altitude: '1200 - 1450',
  },

  CofermentedWineYeastLynchee: {
    country: 'Colombia',
    color: 'purple',
    farm: 'Jairo Arcila',
    tastingNotes: 'Sweet lynchee, tropical fruits, brown sugar, lime',
    processing: 'Washed',
    lot: 'Santa Monica',
    region: 'Quindio',
    varietals: 'CASTILLO',
    size: '250g',
    traceable: 'Jairo Arcila',
    altitude: '1450-1500 meters',
    fermentation: 'Wine Yeast / Lychee',
  },
};
